### ISSUE TITLE
LDA+U cannot be used with spin-orbit coupling in Siesta 

### ISSUE THREAD

**Issue by malaei** [mailhexu/TB2J_examples#1]
Dear Xu

In the Siesta examples, you use LDA+U, while I check almost all versions of Siesta in GitLab and
all of them have the following error inside the Src/setup_hamiltonian.F:
'LDA+U cannot be used with spin-orbit coupling.'

Which version of Siesta did you use in TB2J_examples?

Best regards,
Mojtaba

**Comment by mailhexu** [comment]
Dear Mojtaba,
Indeed the current public versions of Siesta cannot use LDA+U+SOC. 
You can try this branch if you really need it
https://gitlab.com/jjunquer/siesta/-/tree/ldau-so
Otherwise you can wait for this to be merged into the main branch. 

Best regards,
HeXu

**Comment by malaei** [comment]
Thank you.
