### ISSUE TITLE
The J difference of CrI3 between the energy mapping and magnetic force method

### ISSUE THREAD

**Issue by servant1991** [mailhexu/TB2J_examples#2]
Dear Xu:
   This is a nice software. However, when I copy the case of CrI3 monolayer, the J obtained by  the magnetic force method exhibits a huge difference to the energy mapping method [Phys. Rev. B 98,144411 (2018)]. How can I get the consistent results between two methods?

Best regards,
K.Sheng

**Comment by mailhexu** [comment]
Perhaps you will find this paper useful. I. V. Solovyev Phys. Rev. B 103, 104428
It presents the challenges in computing the J values in some materials like CrI3. 
Best regards, 
HeXu
